version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  web:
    build: .
    container_name: application
    env_file: .env
    links:
      - db
    ports:
      - 8080:8080
