server:
  port: ${PORT}
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
application:
  datetime:
    format: "dd-MM-yyyy HH:mm:ss"
    zone: "Europe/Moscow"
  subscribers:
    maxAdvanceNoticeSeconds: 10
